model_file: config/stl/S_ciclo_henrique/s_ciclo_H.stl #arquivo da peça desejada
flex_model_file: config/stl/S_ciclo_henrique/s_ciclo_H_flex.stl #arquivo da "peça" que representa a região flexível na peça original
start_script: out/gcode/start_prusaMK3S.gcode #arquivo cabeçalho de inicio da impressora
end_script: out/gcode/end_prusaMK3S.gcode #arquivo cabeçalho de fim da impressora
infill_angle: [180] #angulo de preenchimento
infill_gap: 0.5 #prenchimento de lacuna
offset: [150, 75, 0] #ponto zero da mesa
external_adjust: 0.5 #ajuste dimensional, eh um offset que ele da nas laterais
perimeter_num: 2 #numero de perimetros
perimeter_gap: 0.5 #gap entre os perimetros e o infill
skirt_distance: 10 #distância da saia
skirt_num: 3 #numero de perimetros da saia
skirt_gap: 0.6 #largura da lacuna entre os contornos da saia
overlap: 0.0 #sobreposição
travel_speed: 12000
retraction: -0.2 #valor de retração do filemento no bico durante movimentos de deslocamento
first_layer_flow: 1 #fluxo na primeira camada********
flow: 1 #fluxo na região padrão da peça*********
speed: 2400 #velocidade na região padrão da peça
flex_flow: 0.6 #fluxo na região flexivel da peça*******
flex_speed: 3300 #velocidade na região flexivel da peça**********
retract_flow: 0.6 #fluxo na região de recuperação da peça**********
retract_speed: 3300 #velocidade na região de recuperação da peça*******
retract_ratio: 0.9 #razao que determina a proporcao entre regiao flexivel e regiao de recuperacao, ex: 0.9 pra uma regiao de 10mm -> 9mm de regiao flexivel 1mm de recuperacao
horizontal_gap_flex_infill: True #cria "vãos" (gaps) horizontais em formtos retangulares na zona flexível
horizontal_num_gap: 2 #quantidade de gaps
horizontal_perc_gap: 0.4 #porcentagem da área vazia em relação à área total da zona flexível
orientation_gap: False #orientação de construção dos gaps: se os feixes da região flexivel estão no sentido horizontal, é False, se tiverem na vertical, é True
best_path: True #ativar o algoritmo de melhor caminho
verbose: True